$(".chief").on("click",function(){
    $(".first").slideToggle();
})
$(".chair").on("click",function(){
    $(".second").slideToggle();
})
$(".chairp").on("click",function(){
    $(".third").slideToggle();
})
$(".Technical").on("click",function(){
    $(".fourth").slideToggle();
})
$(".Workshop").on("click",function(){
    $(".fifth").slideToggle();
})
$(".Registration").on("click",function(){
    $(".six").slideToggle();
})